services:
  frontend: 
    image: tvmc-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my-network
  
  backend:
    image: tvmc-backend
    env_file: 
      - backend/.env
    ports:
      - "3000:5000"
    environment:
      NODE_ENV: production
    networks:
      - my-network

networks: 
  my-network:
    driver: bridge
